routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');

//Route::post('/questions/{question}/answers','AnswersController@store')->name('answers.store');

Route::resource('questions.answers','AnswersController')->except(['index', 'create','show']);

Route::get('/questions/{slug}','QuestionsController@show')->name('questions.show');
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');
Route::post('/questions/{question}/favorites','FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites','FavoritesController@destroy')->name('questions.unfavorite');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class Question extends Model
{
	protected $fillable = ['title', 'body'];
    //protected $appends = ['favorites_favorited'];
	
    public function user(){
    	return $this->belongsTo(user::class);
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    public function getUrlAttribute()
    {
        return route("questions.show", $this->slug);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getStatusAttribute(){
        if( $this->answers_count>0){
            if($this->best_answer_id){
                return 'answered-accepted';
            }
            return 'answered';
        }
        return 'unanswered';
    }
    public function getBodyHtmlAttribute()
    {
        $parsedown = new \Parsedown();
        return $parsedown::instance()->text($this->body);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }
    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }
    public function isFavorited()
    {
        return $this->favorites->where('user_id',auth()->id())->count() > 0;
    }
    public function getFavoritesFavoritedAttribute()
    {
        return $this->isFavorited();
    }
    public function getFavoritesCountAttribute()
    {
        return $this->favorites->count();
    }

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Http\Requests\AskQuestionRequest;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except'=>['index','show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //\DB::enableQueryLog();
        $questions = Question::with('user')->latest()->paginate(5);
        return view('questions.index',compact('questions'));
        //view('questions.index',compact('questions'))->render();
        //dd(\DB::getQueryLog());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $question = new Question();
        return view('questions.create',compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
        $request->user()->questions()->create($request->only('title', 'body'));
        return redirect()->route('questions.index')->with('success','Your question has been submit');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views');
        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $this->authorize("update",$question);
        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        $this->authorize("update",$question);
        $question->update($request->only('title','body'));
        return redirect('/questions')->with('success','Your question has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
         $this->authorize("delete",$question);
        $question->delete();
        return redirect('/questions')->with('success','your Question has beed deleted ');
    }
}

resources/views/questions/_form.blade.php
@csrf
<div class="form-group">
	<label for="question-title">Question Title</label>
	<input type="text" name="title" value="{{old('title', $question->title)}}" id="question-title" class="form-control {{$errors->has('title')?'is-invalid':''}}">
	@if($errors->has('title'))
		<div class="invalid-feedback">
			<strong>{{$errors->first('title')}}</strong>
		</div>
	@endif
</div>
<div class="form-group">
	<label for="question-body">Explain your question</label>
	<textarea name="body" id="question-body" class="form-control {{$errors->has('body')?'is-invalid':''}}" rows="10">{{old('body', $question->body)}}</textarea>
	@if($errors->has('body'))
		<div class="invalid-feedback">
			<strong>{{$errors->first('body')}}</strong>
		</div>
	@endif
</div>
<div class="form-group">
	<button type="submit" class="btn btn-outline-primary btn-lg">{{$buttonText}}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Ask Question</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">back to all Questions</a>
                        </div>
                    </div>
                
                </div>

                <div class="card-body">
                    
                   <form action="{{route('questions.store')}}" method="post">
                   	@include('questions._form',['buttonText'=>'Ask Question'])
                   	
                   </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Edit Question</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">back to all Questions</a>
                        </div>
                    </div>
                
                </div>

                <div class="card-body">
                    
                   <form action="{{route('questions.update', $question->id)}}" method="post">
                   	{{ method_field('PUT') }}
                   	@include('questions._form',['buttonText'=>'Update Question'])
                   	
                   </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.create')}}" class="btn btn-outline-secondary">Ask Question</a>
                        </div>
                    </div>
                
                </div>

                <div class="card-body">
                    @include('layouts._messages')
                    @foreach($questions as $question)
                    	<div class="media">
                            <div class="d-flex flex-column counters">
                                <div class="vote">
                                    <strong>
                                        {{$question->votes}}
                                    </strong>{{Str::plural('vote', $question->votes)}}
                                    
                                </div>
                                <div class="status {{$question->status}}">
                                    <strong>
                                        {{$question->answers_count}}
                                    </strong>{{Str::plural('answer', $question->answers_count)}}
                                    
                                </div>
                                <div class="view">
                                    
                                        {{$question->views." ".Str::plural('view', $question->views)}}
                                    
                                </div>
                            </div>
                    		<div class="medai-body">
                                <div class="d-flex align-items-center">
                                    <h3 class="mt-0">
                                    <a href="{{$question->url}}">
                                        {{$question->title}}
                                    </a>
                                    
                                </h3>
                                <div class="ml-auto">
                                    @can('update',$question)
                                    <a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
                                    @endcan
                                    @can('delete',$question)
                                    <form class="form-delete" method="post" action="{{route("questions.destroy", $question->id)}}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">delete</button>
                                    </form>
                                    @endcan
                                </div>
                                </div>
                    			
                                <p class="lead">
                                    Asked By
                                    <a href="{{$question->user->url}}">{{$question->user->name}}</a>
                                    <small class="muted">{{$question->created_date}}</small>
                                </p>
                    			{{Str::limit($question->body, 250)}}
                    		</div>
                    	</div>
                    	<hr>
                    @endforeach
                    <div class="text-center mx-auto">
                    	{{$questions->links()}}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <div class="d-flex align-items-center">
                            <h1 class="p-2 flex-grow-1">{{$question->title}}</h1>
                            <div class="ml-auto p-2 flex-shrink-0">
                                <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back Questions</a>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="media">
                        <div class="d-flex flex-column vote-controls">
                            <a title="This question is useful" class="vote-up">
                                <i class="fas fa-caret-up fa-2x"></i>
                            </a>
                            <span class="votes-count">1230</span>
                            <a title="This question is not useful" class="vote-down off">
                                <i class="fas fa-caret-down fa-2x"></i>
                            </a>
                            <a title="Click to mark as favorite question (click again to undo)" class="favorite mt-2 {{ Auth::guest() ? 'off':($question->favorites_favorited? 'favorited' :'') }}" onclick="event.preventDefault(); document.getElementById('favorite-question-{{$question->id}}').submit(); "><i class="fas fa-star fa-2x"></i>
                                <span class="favorites-count">{{$question->favorites_count}}</span>
                            </a>
                            <form id="favorite-question-{{ $question->id }}" action="/questions/{{ $question->id }}/favorites" method="POST">
                                @csrf
                                @if ($question->favorites_favorited)

                                    @method('DELETE')
                                @endif
                            </form>
                        </div>
                       <div class="media-body">
                           {!! $question->body_html !!}
                            <div class="float-right">
                                <span class="text-muted">Answered {{$question->created_date}}
                                </span>
                                <div class="media mt-2">
                                    <a href="{{$question->user_url}}" class="pr-2"><img src="{{$question->user->avatar}}"></a>
                                    <div class="media-body mt-1">
                                        <a href="{{$question->user->url}}">{{$question->user->name}}</a>
                                    </div>
                                </div>
                            </div>
                       </div>
                    </div>
                    
                </div>
                

                
            </div>
        </div>
    </div>
    @include('answers._index',[
        'answers' => $question->answers,
        'answersCount' => $question->answers_count,
        ])
    @include('answers._create')    
</div>
@endsection